Add usage examples to homepage
ucan-wg/ucan-community-web pull request #78
Opened 2024-07-24 17:45 UTC by mishmosh

I think adding some usage examples (with some hints at scale/hardening) may help with credibility and convincing for people researching & evaluating UCANs for their projects. I know there's a larger redesign planned (mentioned in #77) but this content should still be relevant.

Sending a PR to make this suggestion more concrete. I won't be offended if this is closed, or if rewrites are committed directly.

2024-12-18 08:50 UTC, bumblefudge approved these changes

2024-12-22 17:30 UTC, icidasset requested changes
Thanks for the examples! Though, WNFS isn't using UCANs just yet. A more correct example would be https://github.com/oddsdk/ts-odd which wraps WNFS (though now outdated). Also, Web3Storage is https://storacha.network/ now, so we should probably link to that page instead.

Another example could be https://github.com/ucan-wg/awake (which the ODD SDK had implemented an early version of).

2025-01-25 01:10 UTC, mishmosh commented
@icidasset Thanks for the pointers and sorry for the long delay. The list is now updated with your suggested changes.

2025-01-25 11:27 UTC, icidasset approved these changes
Thanks! 🙏

2025-01-25 11:27 UTC, merged